### ISSUE TITLE
The card id shouldn't be higher than 0x10000000=268435456

### ISSUE THREAD

**Issue by mercury233** [Fluorohydride/ygopro-pre-script#1]
Most script will use card id to `SetCountLimit`. But the id higher than 0x10000000 will mean 0x10000000+XXXX to the program, and `0x10000000` means `EFFECT_COUNT_CODE_OATH`.

Btw, I suggest that we uses 
908XX for Shining Victories, 
200XX for VJMP, 
20?XX for other promotional cards series, 
331XX for SD31(OCG), 
302XX for SR02(OCG), 
40?XX for DP XX,
50?XX for SP XX, 
and so on. 
For token cards, add 1 before it's host.

**Comment by StormWulf** [comment]
I would like more discussion from the other contributors involved, however here are my reasons to continue supporting the 9-digit ID convention rather than Mercury's proposed 5-digit convention

- The `700` number groups all of the pre-release cards together while still grouping them together with their pack set
- The ninth digit gives room for sets that contain more than 99 cards, such as VJMP. This also gives room for tokens.
- While there aren't many 5-digit official IDs, the 9-digit convention removes the small risk of Konami claiming it. In addition, since Konami will never use 9-digits, these cards will stand out easier in the database.

Does anyone understand the `EFFECT_COUNT_CODE_OATH` risk that Mercury mentioned? The 9-digit convention has been used by FH for cards Konami denied an ID for (particularly the Divine-Beast cards) and so I assume that this risk isn't significant.

**Comment by destdev** [comment]
I think he never intended to get rid of the prefix of 700, thus making a regular 8 digit code with the above examples ... at least if I don't get that that completely wrong here ^^
If we stay in the 9-digit area and need to stay below 268435456 to avoid conflicts ... why don't we just use 100 as prefix instead of 700?
Solves that one, has still the 9 digits, everything should be fine there ... or do I miss anything?

EFFECT_COUNT_CODE_OATH is generally used in spells/traps that have a "card name" once per turn restriction. I'm not sure why only s/t use that and not monsters, I've never got any explanation about that ... I guess there is some internal mechanic involved here?

**Comment by ChibiChanNya** [comment]
Mercury, what if we change 700 for 100? Then the largest ID of 100999999 would be 0x605233F, smaller than 0x10000000.

**Comment by StormWulf** [comment]
At first, I had concerns that Destdev's proposal would overwrite the Anime cards on Salvation Server, but after looking through the cards, I've found that the highest ID with the `100` prefix is `100008001`, which wouldn't cause any problems with the ID convention rules.

**Comment by mercury233** [comment]
I think 9-dight id may conflict with other DIY cards, or Anime cards etc.

But my team never deal with DIY or Anime, so 9-dight is OK for me.

**Comment by DailyShana** [comment]
`SetCountLimit(1,EFFECT_COUNT_CODE_OATH+xxx)` is used to realize "You can only **activate** 1 XXX per turn.", if the **activation** of one XXX is negated, you can activate another XXX.
Without `EFFECT_COUNT_CODE_OATH`, `SetCountLimit(1,xxx)` is for "You can only **use** this effect of XXX once per turn." if the activation of one XXX is negated, you still cannot activate another XXX since activation of a card is included in using an effect.
`EFFECT_COUNT_CODE_OATH` has nothing to do with card name, it canbe used to reaslize "You can only activate this effect of XXX once per turn." although this kind of limit has not appeared in ocg/tcg.

So if you really want to using id>=268435456, you have to avoid using card id in ‘SetCountLimit' directly and then you have take care of count id used in 'SetCountLimit' to avoid other possible conflics.

Just a reminder, using 10-digit id (<2^32=4294967296 basically) will cause another problem in MSG_SELECT_CHAIN, although avoidable by modifying this message.
