### ISSUE TITLE
Mischief of the Time Goddess - overhaul of old effects

### ISSUE THREAD

**Issue by EerieCode** [Fluorohydride/ygopro-pre-script#201]
A few hours ago, Konami's official blog released [an article](https://yugiohblog.konami.com/articles/?p=8832) revealing "[Mischief of the Time Goddess](https://yugipedia.com/wiki/Mischief_of_the_Time_Goddess)", a card with an extremely problematic effect:

_At the end of your Battle Phase, if all monsters you control are "Valkyrie" monsters (min. 1): Send this card to the GY, also, immediately after this effect resolves, skip to the start of the Battle Phase of your next turn._

  As mentioned in the article, this effect completely skips all phases between the current Battle Phase and the player's next, preventing all effects from applying: the article suggest using it in combination with "Ride of the Valkyries", whose Continuous effects returns monsters to the Deck during the End Phase of the turn it's activated, so that's not our interpretation, that's _exactly_ how it's meant to work. 
  The problem is, this causes several problematic interactions with other cards: first and foremost Spirit Monsters, who should return to the hand only at the end of the turn they're summoned, but also cards like "Cynet Codec" that reset variables during certain phases, or even simply cards that use ActivityCounters for effects like summon limits (I'm sure I'm missing other potential interactions, in which case feel free to add them in the comments.)
  I'm opening this issue so that we can discuss how to proceed and manage to create a common implementation between all simulators. What are your thoughts on the matter?

**Comment by AlphaKretin** [comment]
I'd like to note that while Phase-based effects do not apply, the text and article do seem to indicate it's the next turn. The implications for activating Set Trap Cards, named effect count limits, and the turn count for Final Countdown are unclear.

**Comment by destdev** [comment]
I think what we need to do here is implementing some kind of check if an effect or flag or whatever should reset if a turn (or certain phases of a turn) is skipped or not. The article states it, if the end phase is skipped the effect from Ride of the Valkyries that returns the monsters to the hand is not applied.

I'm not sure how that is handled by the core currently, but looking at the Skip Turn effect from Arcana Force XXI I'll assume it is currently standard procedure to apply a reset, even if that turn/phase is skipped. At least for the end phase, since the Skip Turn effect is reset in the end phase of the skipped turn. (Please correct me if I'm wrong)

This needs to change. There are certain terms in the card texts (or certain effects) that should not reset an effect/flag if the phase doesn't happen. A few examples of cards that may have problems with such skips:
1) Hino-Kagu-Tsuchi
The Predraw effect should not reset in a Draw Phase that never happens.
2) Fire King High Avatar Garunix, Evilswarm Thunderbird, new Nephthys cards, etc
The Flag effect should not reset in a Standby Phase that never happens.

for such cases I'd suggest some new constant like RESET_IGNORE_SKIP or something along that line that would tell the core to not reset an effect/flag in a skipped phase...
